### ISSUE TITLE
Modal display on pause

### ISSUE THREAD

**Issue by alexfigtree** [makebrainwaves/neurolearning#8]

**Comment by jdpigeon** [comment]
Semantic UI's Modal is awesome: https://react.semantic-ui.com/modules/modal/

**Comment by alexfigtree** [comment]
> Semantic UI's Modal is awesome: https://react.semantic-ui.com/modules/modal/

Cool, thanks!

**Comment by alexfigtree** [comment]
@jdpigeon semantic ui now being used for modals
